markdown: kramdown
kramdown:
  input: GFM
  startinline: true

highlighter: rouge

permalink: /guide/:title

name: "Rogue PVE Guides"
description: "Rogue PVE Guides"
url: https://riff.tf

exclude: [ 'Gemfile', 'Gemfile.lock', 'README.md', 'script' ]
